### PR TITLE
prevent scroll and resize issues on Android and iOS

### PR DESCRIPTION
**Pull request by clemensf**

### CODE REVIEW

**Comment by jurekbarth** [comment]
Could you please reconsider that scrolljacking approach overall. It's still buggy even in Chrome, where the scrollbar jumps crazy and you're caught in the middle. There are a lot of articles why thats a bad pattern overall, here's one of them: https://www.robinrendle.com/notes/scrolljacking

**Comment by clemensf** [comment]
@jurekbarth do you mean scroll based animation in general or the specific „scroll capturing“ here?

@luke-m and @rhafner @timomayer : 
what do you think? Should we re consider and re-implement the scroll animation?

**Comment by jurekbarth** [comment]
@clemensf @luke-m I'm not against the animation, it's just about how the scroll itself behaves. I as a user expect that the scroll behaves as it normally behaves. I would really appreciate if you could reconsider your decisions, based on the article i've mentioned before. Otherwise just google "scroll hijacking" and you will find a lot of good reasons why it's poor UX.

**Comment by luke-m** [comment]
@jurekbarth we talked about the issue and came to the conclusion to remove the scrolljacking while keeping the animation.  
Short background: in the past, we already came to a point where we had the animation implemented without any scrolljacking but then it felt like you needed to scroll too "precisely" to the text sections between the transitions to get to the information that we want to provide. That's why we decided to implement the scrolljacking to guide the user to the information. We were already aware of the pitfalls of this technique when we decided on it initially but we weren't too concerned. Now that we see the end product and also the technical difficulties this produces, we decided to move away from it again. We're going to try solve the issue that I described earlier (information "frames" being lost within the animation) by making the actual frame-duration of the text "slides" longer.

**Pull request merged**
