### PR TITLE
 smooth scrollig effect on buttons

### PR DESCRIPTION
**Pull request by IvailoStoyanov**

### CODE REVIEW

**Comment by luke-m** [comment]
Seems to work in my chromium based Brave browser, firefox and chrome itself. Doesn't work in Safari.

**Comment by luke-m** [comment]
image

Looks weird in Safari. @IvailoStoyanov  can you check this out please.

**Comment by luke-m** [comment]
^ this only happens in this branch, that's why I'm posting it here.

**Comment by IvailoStoyanov** [comment]
The issue seems to be on Develop as well I will not fix it through this branch however

**Pull request merged**
